services:
  file-transfer:
    image: ghcr.io/yantianqi1/file-transfer:latest
    container_name: file-transfer
    ports:
      - "8009:8080"
    environment:
      HOST: 0.0.0.0
      PORT: 8080
      UPLOADS_DIR: /data/uploads
      CONFIG_DIR: /data/config
      CHUNKS_DIR: /data/chunks
    volumes:
      - ./file-transfer-data/uploads:/data/uploads
      - ./file-transfer-data/config:/data/config
      - ./file-transfer-data/chunks:/data/chunks
    restart: unless-stopped
